### ISSUE TITLE
Zero  GPU-Util

### ISSUE THREAD

**Issue by czy97** [funcwj/ge2e-speaker-verification#3]
Do you run your code before?I run your code using the sre2004 as train and dev(just have a try),but the nvidia-smi command shows that the GPU-Util is 0.

**Comment by funcwj** [comment]
Seems there is no GPU available. I run my code on LibriSpeech with single or multiple cards and no error is reported.

**Comment by czy97** [comment]
> Seems there is no GPU available. I run my code on LibriSpeech with single or multiple cards and no error is reported.

Maybe it is because the processing time of the dataloader.I test the runtime of the _sample func of SpeakerLoader class,it cost 30-40s.So most of the time,the gpu card have nothing to do.

**Comment by czy97** [comment]
> Seems there is no GPU available. I run my code on LibriSpeech with single or multiple cards and no error is reported.

There is no error reported. Most of the time the GPU-Util is 0 (the gpu memory is indeed allocated),so the code runs very slowly.

**Comment by funcwj** [comment]
I know this issue and profiled dataloader when conducted experiments. But in my side cost of one step is not as slowly as yours. Are you using the compressed version of the features?

**Comment by funcwj** [comment]
For 1000 steps, I only cost 125s in my side, so check your settings please.

**Comment by czy97** [comment]
> I know this issue and profiled dataloader when conducted experiments. But in my side cost of one step is not as slowly as yours. Are you using the compressed version of the features?

Yes, the data is  compressed version

**Comment by funcwj** [comment]
I write this issue in [kaldi-python-io](https://github.com/funcwj/kaldi-python-io) and in the future I may optimize loading of compressed matrices.

**Comment by czy97** [comment]
Ok, thanks for your reply.
